version: '3.3'

services: 
    app:
        build: 
            context: .
            dockerfile: Dockerfile
        restart: 'always'
        container_name: 'node-app'
        ports:
            - '3000:3000'